
package com.fitec.tp.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICalculateur", targetNamespace = "http://service.tp.fitec.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ICalculateur {


    /**
     * 
     * @param tauxPct
     * @param ht
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "tva", targetNamespace = "http://service.tp.fitec.com/", className = "com.fitec.tp.service.Tva")
    @ResponseWrapper(localName = "tvaResponse", targetNamespace = "http://service.tp.fitec.com/", className = "com.fitec.tp.service.TvaResponse")
    @Action(input = "http://service.tp.fitec.com/ICalculateur/tvaRequest", output = "http://service.tp.fitec.com/ICalculateur/tvaResponse")
    public double tva(
        @WebParam(name = "ht", targetNamespace = "")
        double ht,
        @WebParam(name = "tauxPct", targetNamespace = "")
        double tauxPct);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAuteur", targetNamespace = "http://service.tp.fitec.com/", className = "com.fitec.tp.service.GetAuteur")
    @ResponseWrapper(localName = "getAuteurResponse", targetNamespace = "http://service.tp.fitec.com/", className = "com.fitec.tp.service.GetAuteurResponse")
    @Action(input = "http://service.tp.fitec.com/ICalculateur/getAuteurRequest", output = "http://service.tp.fitec.com/ICalculateur/getAuteurResponse")
    public String getAuteur();

}
